#define VERSION_CONTROL_FILE_URL "https://raw.githubusercontent.com/isis97/TicTacConsole/release/release/version.info"

#define SWITCH_NEVER_PHYSICALLY_INSTALL_UPDATE NO
#define SWITCH_PLAY_MUSIC_BY_DEFAULT YES
#define SWITCH_USER_CANNOT_MOVE NO
#define SWITCH_ACTIVATE_FIRST_SMART_ENEMY YES
#define SWITCH_ACTIVATE_SECOND_SMART_ENEMY YES
#define SWITCH_ACTIVATE_THIRD_SMART_ENEMY YES
#define SWITCH_SKIP_UPDATES NO
#define SWITCH_SKIP_TO_GAME NO
#define SWITCH_SINGLE_INSTANCE NO
#define PLAYER0_GROUP 0
#define PLAYERAI1_GROUP 1
#define PLAYERAI2_GROUP 2
#define PLAYERAI3_GROUP 3
