string disp = "";
string curip = "<?>";
string curiphostname = "<?>";
deque <string> group_chat;
deque <string> server_group_chat;
string combuf = "";
int netclients = 0;
bool setting_play_music = SWITCH_PLAY_MUSIC_BY_DEFAULT;
bool setting_debug_mode = false;
bool setting_invert_colours = true;
bool setting_lower_mouse_sensivity = false;
inline bool isServerRunning();
string path = getexepath();//"C:\\Users\\Piotr\\Documents\\Projects\\Temporary\\SCGL - Copy\\";
string __VERSION_NAME = "";
float __VERSION = 0.0f;
int __VERSION_BUILD = 0000;
bool runapp = true;
int menu_state = 0;
bool update_menu_state = false;
bool is_game_made = false;
bool is_game_made_with_draw = false;
bool wait_each_ai_enemy = false;
bool is_net_game_client = false;
bool is_net_game_server = false;
bool can_client_move = false;
int client_user_move_x = -1;
int client_user_move_y = -1;
char client_user_move_marker = '?';
int nx = 3;
int ny = 3;
int markx = 0;
int marky = 0;
int markfx = 0;
int markfy = 0;
char markch = AVAILABLE_SIGNS_DEFAULT;
char markchsel = AVAILABLE_SIGNS_DEFAULT;
int levmap_size = 0;
int lastlevmapasgn = -1;
short *levmap;
vector<aienemy*> playerAiReg;
int playerRegMove = 0;
int playersNum = 0;
